name: huskyCI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  huskyCI:
    runs-on: ubuntu-latest
    environment: HUSKYCI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Faz Analise         
        
        run: |
          #curl  -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}}
          headers=$(curl -i -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}})
          sleep 30s
          echo "request_id=$(echo "$headers" | grep 'X-Request-Id:' | awk -v RS='\r\n' '{print $2}')" >> "$GITHUB_ENV"
                     
      - name: Resultado Analise
        env:
          req_id: ${{ env.request_id }}
          husky_url: ${{ secrets.HUSKY_URL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
          
        run: | 
           curl  "${{ env.husky_url }}/${{ env.req_id }}" | json_pp
           
           stop_pipeline(){
              echo "foram encontradas vulnerabilidades que podem comprometer a aplicação, por favor corrija e commite novamente"  
              # Obter o hash do commit anterior
              PREVIOUS_COMMIT=$(git rev-parse HEAD^)
              git revert --no-edit $COMMIT_HASH
              if [ github.event.pull_request ]; then
                echo 'oi'
                # Extrair o número do pull request da variável GITHUB_REF
                PR_NUMBER=${GITHUB_REF#refs/pull/}
                PR_NUMBER=${PR_NUMBER%/merge}
                gh pr close $PR_NUMBER -R $GITHUB_REPOSITORY --token $GITHUB_TOKEN -c 'parece que você esta tentando mergar um codigo vulneravel por favor revise-o '
                gh pr edit ${{env.PR}} --add-label 'invalid'
              fi
              uses: tibdex/github-commit-status-action@v3
              with:
                state: failure
                description: Você commitou um codigo vulneravel, por favor revise-o e commite novamente.

              exit 1
              }
           r_json=$(curl  "${{ env.husky_url }}/${{ env.req_id }}")
           result_value=$(echo "$r_json" | jq -r '.result')
           if [ $result_value == "failed" ]; then
                       
              stop_pipeline
           else
            echo "Parabens seu codigo aparente esta limpo"
            exit 0
           fi    
