name: huskyCI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  huskyCI:
    runs-on: ubuntu-latest
    environment: HUSKYCI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run huskyCI
      
      
        #env:
         # HUSKY_URL: ${{secrets.HUSKY_URL}}                    
          
      
        run: |
          curl -i -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}}
          headers=$(curl -i -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}})
          sleep 30s
          #request_id=$(echo "$headers" | grep 'X-Request-Id:' | awk '{print $2}')
          echo "request_id=$(echo "$headers" | grep 'X-Request-Id:' | awk '{print $2}')" >> "$GITHUB_ENV"
          
          
           
      - name: Resultado Analise
        env:
          req_id: ${{ env.request_id }}
          husky_url: ${{ secrets.HUSKY_URL }}
          google: http://google.com
          #url: ${{ format('{0}/{1}', secrets.HUSKY_URL, env.request_id)}}
        run: | 
           #curl  ${{ env.husky_url }}/${{ env.req_id }}
           curl "${{env.google}}/?q=${{env.req_id}}"
           #echo "${{ env.husky_url }}/${{ env.req_id }}"
           #echo $url
