name: huskyCI

on:
  push:
    branches:
      - main
  pull_request:
     branches:
        - main
jobs:
  huskyCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run huskyCI
        run: |
          docker run --rm \
            -v "$(pwd)":/src \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e HUSKYCI_URL=https://github.com/matholiveira91/hsk \
           
