name: huskyCI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  huskyCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run huskyCI
      
        env:
           HUSKY_URL: ${{ env.HUSKY_URL }}                    
          
      
        run: |
          curl -i -H "Content-Type: application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' '$HUSKY_URL'       
