name: huskyCI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main

jobs:
  huskyCI:
    runs-on: ubuntu-latest
    environment: HUSKYCI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Faz Analise         
        
        run: |
          curl  -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}}
          headers=$(curl -i -H "Content-Type:application/json" -d '{"repositoryURL":"https://github.com/matholiveira91/hsk.git","repositoryBranch":"main"}' ${{secrets.HUSKY_URL}})
          sleep 30s
          echo "request_id=$(echo "$headers" | grep 'X-Request-Id:' | awk -v RS='\r\n' '{print $2}')" >> "$GITHUB_ENV"
          
          
           
      - name: Resultado Analise
        env:
          req_id: ${{ env.request_id }}
          husky_url: ${{ secrets.HUSKY_URL }}
          
        run: | 
           curl  "${{ env.husky_url }}/${{ env.req_id }}"
           stop_pipeline(){
              echo "foram encontradas vulnerabilidades que podem comprometer a aplicação, por favor corrija e commite novamente"
              exit 1
              }
           r_json=$(curl  "${{ env.husky_url }}/${{ env.req_id }}")
           resultado = $(echo "$r_json" | jq -r 'result')
           echo $resultado
