name: huskyCI

on:
  push:
    branches:
      - main

jobs:
  huskyCI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run huskyCI
        run: 
          /client/cmd/huskyci-client-bin
